import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — ensemble',
  description: 'Privacy Policy for the Ensemble language learning app.',
};

const EFFECTIVE_DATE = 'May 18, 2026';
const COMPANY = 'Rushford Collyer LLC';
const APP_NAME = 'Ensemble';
const WEBSITE = 'https://ensemblelanguage.com';
const PRIVACY_EMAIL = 'privacy@ensemblelanguage.com';

export default function PrivacyPage() {
  return (
    <div className="flex min-h-dvh flex-col">
      {/* Header */}
      <header className="border-b">
        <div className="container flex h-16 items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="bg-primary/10 inline-flex size-10 items-center justify-center rounded-full">
              <p className="text-primary font-brand h-12 text-4xl font-semibold">e</p>
            </div>
            <span className="font-brand text-xl font-semibold leading-none text-gray-600">
              ensemble
            </span>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="container mx-auto max-w-3xl px-4 py-16">
        <h1 className="font-brand text-primary mb-2 text-4xl font-semibold">Privacy Policy</h1>
        <p className="text-muted-foreground mb-10 text-sm">
          Effective date: {EFFECTIVE_DATE}
        </p>

        <div className="prose prose-slate max-w-none space-y-10 text-gray-700">

          {/* 1. Introduction */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">1. Introduction</h2>
            <p>
              {COMPANY} ("we," "us," or "our") operates the {APP_NAME} language learning
              application and website at{' '}
              <a href={WEBSITE} className="text-primary hover:underline">
                {WEBSITE}
              </a>{' '}
              (collectively, the "Service"). This Privacy Policy explains what information we
              collect, how we use it, who we share it with, and the choices you have.
            </p>
            <p className="mt-3">
              By using the Service, you agree to the collection and use of information in
              accordance with this policy. If you do not agree, please do not use the Service.
            </p>
          </section>

          {/* 2. Information We Collect */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">2. Information We Collect</h2>

            <h3 className="mb-2 mt-4 text-base font-semibold text-gray-800">
              Information you provide directly
            </h3>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                <strong>Account information:</strong> When you create an account, we collect your
                email address and display name. You may optionally upload a profile photo.
              </li>
              <li>
                <strong>Flashcard content:</strong> The decks, cards, folders, and groups you
                create, including any text, translations, and notes you enter.
              </li>
              <li>
                <strong>Profile photo:</strong> If you choose to upload one, your photo is stored
                on our servers. You can remove it at any time from Settings.
              </li>
            </ul>

            <h3 className="mb-2 mt-4 text-base font-semibold text-gray-800">
              Information generated by your use of the Service
            </h3>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                <strong>Practice history:</strong> Your flashcard practice sessions, self-rated
                recall scores, and spaced-repetition scheduling data (SM-2 algorithm parameters)
                so the app can show you cards at the right time.
              </li>
              <li>
                <strong>Audio files:</strong> When you use the text-to-speech feature, audio
                pronunciations are generated and stored on our servers so they can be replayed
                without regenerating each time.
              </li>
              <li>
                <strong>Session tokens:</strong> When you sign in, we store a secure session
                token on your device to keep you signed in. This token is stored in your device's
                secure enclave (iOS Keychain via expo-secure-store).
              </li>
            </ul>

            <h3 className="mb-2 mt-4 text-base font-semibold text-gray-800">
              Information collected automatically
            </h3>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                <strong>Usage analytics:</strong> We use Vercel Analytics to collect anonymous,
                aggregated data about how visitors use our website (page views, referring pages,
                browser type). This data does not identify you personally.
              </li>
              <li>
                <strong>Log data:</strong> Our hosting infrastructure may automatically log
                standard server request information such as IP address, request timestamp, and
                HTTP status codes for security and diagnostic purposes. These logs are retained
                for a short period and are not used for marketing.
              </li>
            </ul>
          </section>

          {/* 3. How We Use Your Information */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">
              3. How We Use Your Information
            </h2>
            <p>We use the information we collect to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Create and manage your account and authenticate your identity</li>
              <li>Provide and improve the Service, including spaced-repetition scheduling</li>
              <li>
                Generate translations and audio pronunciations for cards you create using
                Google Cloud Translate and Text-to-Speech
              </li>
              <li>Send transactional emails (sign-in magic links, group invitations)</li>
              <li>Respond to your support requests and questions</li>
              <li>Monitor for abuse, fraud, and security issues</li>
              <li>Analyze aggregate usage patterns to improve the Service</li>
            </ul>
            <p className="mt-3">
              We do not use your flashcard content or practice history for advertising purposes,
              and we do not sell your personal information to third parties.
            </p>
          </section>

          {/* 4. Third-Party Services */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">4. Third-Party Services</h2>
            <p>
              We rely on the following third-party services to operate the Service. Each has its
              own privacy policy governing their handling of data.
            </p>

            <div className="mt-4 space-y-4">
              <ThirdParty
                name="Google OAuth (Sign in with Google)"
                purpose="Allows you to authenticate using your Google account. When you choose this sign-in method, Google shares your email address and profile name with us."
                link="https://policies.google.com/privacy"
              />
              <ThirdParty
                name="Google Cloud Translate"
                purpose="Translates flashcard text when you enable the translation feature. Card text is sent to Google's servers for translation."
                link="https://cloud.google.com/terms/cloud-privacy-notice"
              />
              <ThirdParty
                name="Google Cloud Text-to-Speech"
                purpose="Generates audio pronunciations for flashcard content. Card text is sent to Google's servers to synthesize audio."
                link="https://cloud.google.com/terms/cloud-privacy-notice"
              />
              <ThirdParty
                name="Amazon Web Services (AWS S3)"
                purpose="Stores profile photos and generated audio files. Files are stored in the us-east-1 (Northern Virginia) region."
                link="https://aws.amazon.com/privacy/"
              />
              <ThirdParty
                name="Resend"
                purpose="Sends transactional emails such as sign-in magic links and group invitations. Your email address is passed to Resend solely to deliver these messages."
                link="https://resend.com/privacy"
              />
              <ThirdParty
                name="Neon"
                purpose="Hosts our PostgreSQL database containing your account information, decks, cards, and practice history. Data is stored in the us-east-1 region."
                link="https://neon.tech/privacy-policy"
              />
              <ThirdParty
                name="Vercel"
                purpose="Hosts and serves the web application. Vercel Analytics collects anonymous, aggregated usage data about web page visits."
                link="https://vercel.com/legal/privacy-policy"
              />
            </div>
          </section>

          {/* 5. Data Storage and Security */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">
              5. Data Storage and Security
            </h2>
            <p>
              Your data is stored on servers located in the United States (AWS and Neon,
              us-east-1 region; Vercel infrastructure). If you are located outside the United
              States, your information is transferred to and processed in the United States.
            </p>
            <p className="mt-3">
              We use industry-standard measures to protect your data, including encrypted
              connections (HTTPS/TLS) for all data in transit, encrypted database connections,
              and secure token storage on mobile devices via the iOS Keychain. However, no
              method of transmission or storage is 100% secure, and we cannot guarantee absolute
              security.
            </p>
          </section>

          {/* 6. Children's Privacy (COPPA) */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">
              6. Children's Privacy
            </h2>
            <p>
              The Service is available to users of all ages. We are committed to complying with
              the Children's Online Privacy Protection Act (COPPA) and similar laws regarding the
              privacy of children under 13.
            </p>
            <p className="mt-3">
              <strong>Users under 13:</strong> If you are under 13 years of age, you must have
              verifiable consent from a parent or legal guardian before creating an account or
              using the Service. By creating an account on behalf of a child under 13, the
              parent or guardian represents that they have reviewed this Privacy Policy and
              consent to our collection and use of the child's information as described herein.
            </p>
            <p className="mt-3">
              We do not knowingly collect personal information from children under 13 without
              verifiable parental consent. If we become aware that we have collected personal
              information from a child under 13 without parental consent, we will take steps to
              delete that information promptly. If you believe we may have collected information
              from a child under 13 without appropriate consent, please contact us at{' '}
              <a href={`mailto:${PRIVACY_EMAIL}`} className="text-primary hover:underline">
                {PRIVACY_EMAIL}
              </a>
              .
            </p>
            <p className="mt-3">
              <strong>Parents and guardians</strong> may review the personal information we have
              collected about their child, request its deletion, or refuse further collection by
              contacting us at{' '}
              <a href={`mailto:${PRIVACY_EMAIL}`} className="text-primary hover:underline">
                {PRIVACY_EMAIL}
              </a>
              . We will respond to verified requests within 30 days.
            </p>
          </section>

          {/* 7. Your Rights */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">
              7. Your Privacy Rights
            </h2>

            <h3 className="mb-2 mt-4 text-base font-semibold text-gray-800">All users</h3>
            <p>Regardless of where you are located, you have the right to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                <strong>Access and update your data:</strong> View and edit your profile
                information at any time in the Settings screen.
              </li>
              <li>
                <strong>Delete your account:</strong> Permanently delete your account and all
                associated data directly from the Settings screen in the app, or by contacting us
                at{' '}
                <a href={`mailto:${PRIVACY_EMAIL}`} className="text-primary hover:underline">
                  {PRIVACY_EMAIL}
                </a>
                . Deletion is irreversible and removes all your decks, cards, practice history,
                and account information.
              </li>
            </ul>

            <h3 className="mb-2 mt-4 text-base font-semibold text-gray-800">
              EU and UK users (GDPR / UK GDPR)
            </h3>
            <p>
              If you are located in the European Economic Area (EEA) or the United Kingdom, the
              General Data Protection Regulation (GDPR) or UK GDPR applies to our processing of
              your personal data. Our legal basis for processing your data is:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                <strong>Contract performance:</strong> Processing your email, name, and content
                is necessary to provide the Service you signed up for.
              </li>
              <li>
                <strong>Legitimate interests:</strong> Security monitoring and aggregate analytics
                to maintain and improve the Service.
              </li>
              <li>
                <strong>Consent:</strong> Optional features such as Google Sign-In and profile
                photos, which you can revoke at any time.
              </li>
            </ul>
            <p className="mt-3">Under GDPR / UK GDPR, you have the right to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Access a copy of the personal data we hold about you</li>
              <li>Correct inaccurate personal data</li>
              <li>Request erasure of your personal data ("right to be forgotten")</li>
              <li>
                Restrict or object to certain processing (e.g., opting out of analytics)
              </li>
              <li>
                Data portability — receive your data in a structured, machine-readable format
              </li>
              <li>
                Lodge a complaint with your local supervisory authority (e.g., the ICO in the
                UK, or your EU Member State's data protection authority)
              </li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, contact us at{' '}
              <a href={`mailto:${PRIVACY_EMAIL}`} className="text-primary hover:underline">
                {PRIVACY_EMAIL}
              </a>
              . We will respond within 30 days. We may need to verify your identity before
              fulfilling a request.
            </p>
            <p className="mt-3">
              Because your data is stored in the United States, international data transfers from
              the EEA/UK are covered by Standard Contractual Clauses (SCCs) or equivalent
              mechanisms as required by applicable law.
            </p>
          </section>

          {/* 8. Data Retention */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">8. Data Retention</h2>
            <p>
              We retain your personal data for as long as your account is active or as needed to
              provide the Service. If you delete your account, we will delete or anonymize your
              personal data within 30 days, except where we are required to retain it for legal
              or compliance purposes (e.g., fraud prevention records).
            </p>
            <p className="mt-3">
              Audio files generated by the text-to-speech feature are retained as long as the
              associated flashcard exists. Deleting a card removes its associated audio.
            </p>
          </section>

          {/* 9. Changes */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">
              9. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. When we do, we will revise
              the "Effective date" at the top of this page. For significant changes, we will
              notify you by email or through a notice in the app before the change takes effect.
              Your continued use of the Service after the effective date constitutes your
              acceptance of the updated policy.
            </p>
          </section>

          {/* 10. Contact */}
          <section>
            <h2 className="mb-3 text-xl font-semibold text-gray-900">10. Contact Us</h2>
            <p>
              If you have any questions, concerns, or requests regarding this Privacy Policy or
              our data practices, please contact us:
            </p>
            <address className="mt-3 not-italic">
              <p className="font-medium">{COMPANY}</p>
              <p>
                Email:{' '}
                <a href={`mailto:${PRIVACY_EMAIL}`} className="text-primary hover:underline">
                  {PRIVACY_EMAIL}
                </a>
              </p>
              <p>
                Website:{' '}
                <a href={WEBSITE} className="text-primary hover:underline">
                  {WEBSITE}
                </a>
              </p>
            </address>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t py-8">
        <div className="container text-center text-sm text-gray-500">
          <p>
            &copy; {new Date().getFullYear()} {COMPANY}. All rights reserved.
          </p>
          <p className="mt-1">
            <Link href="/" className="hover:underline">
              Back to ensemble
            </Link>
          </p>
        </div>
      </footer>
    </div>
  );
}

function ThirdParty({
  name,
  purpose,
  link,
}: {
  name: string;
  purpose: string;
  link: string;
}) {
  return (
    <div className="rounded-lg border border-gray-200 bg-gray-50 px-4 py-3">
      <p className="font-semibold text-gray-900">{name}</p>
      <p className="mt-1 text-sm text-gray-600">{purpose}</p>
      <a
        href={link}
        target="_blank"
        rel="noopener noreferrer"
        className="text-primary mt-1 inline-block text-xs hover:underline"
      >
        Privacy Policy →
      </a>
    </div>
  );
}
